name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Inject Supabase env to JS
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          sed -i "s|SUPABASE_URL_PLACEHOLDER|$SUPABASE_URL|g" ./_site/assets/main.js
          sed -i "s|SUPABASE_KEY_PLACEHOLDER|$SUPABASE_KEY|g" ./_site/assets/main.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
